fixtures:
  repositories:
    stdlib:
      repo: 'git@github.com:puppetlabs/puppetlabs-apt.git'
      ref: '2.0.1'
    apt:
      repo: 'git@github.com:puppetlabs/puppetlabs-stdlib.git'
      ref: '4.5.1'
  symlinks:
    aurora: "#{source_dir}"
