HOSTS:
	ubuntu-14.04:
		roles:
			- master 
			- database
			- dashboard
	platform: ubuntu-ubuntu-14.04-x64
	image: ubuntu:14.04
	hypervisor:docker
	docker_image_commands:
	- 'RUN ["apt-get", "install", "software-properties-common"]
	- 'RUN ["add-apt-repository", "ppa:openjdk-r/ppa", "-y"]'
	- 'RUN ["apt-get", "update", "openjdk-8-jdk"]
	- 'RUN["apt-get", "install", "y", "openjdk-8-jdk"]

CONFIG:
	type: foss 