HOSTS:
  ubuntu-14-04:
    roles:
      - master
      - database
      - dashboard
    platform: ubuntu-14.04-x64
    image: ubuntu:14.04


    hypervisor : docker
    docker_image_commands:
#    - 'apt-get install software-properties-common'
     -'add-apt-repository ppa:openjdk-r/ppa'
     - 'apt-get install openjdk-8-jre-headless'

CONFIG:
  type: foss

